### ISSUE TITLE
How about setting value outside widget?

### ISSUE THREAD

**Issue by WiRight** [pmatatias/input-quantity#45]
In my case i getting new value from another place (for example: websocket)
And setting value as `initVal` has no effect

How set new value outside? (Something like controller?)

**Comment by pmatatias** [comment]
Hi @WiRight, thank you for submitting the issue.

I think it is caused because the widget is not rebuilt. so `initVal` doesn't change.
for a simple solution, you can force rebuild the `InputQty` widget every time it receives a new `initVal` value. to do that, just specify the `key` property.

```
InputQty(
    key: ValueKey("$streamedInitVal"), // every different value key will force to rebuild the widget.
    initVal: streamedInitVal,
  ),
```

---

I will try to develop a new feature to extract `TexteditingController`, so that it is available from outside the package. but it may take time

**Comment by WiRight** [comment]
@pmatatias hey and thanks for the quick response! using key solved my problem now!
