### ISSUE TITLE
Overflow when step is a double type

### ISSUE THREAD

**Issue by yykk7711** [pmatatias/input-quantity#46]
I encountered the problem that when I set step = 0.1, the value will overflow sometimes.

For example, 0.1 + 0.1 = 0.20000000001. Is there any way to round off the value shown in the UI?

**Comment by pmatatias** [comment]
Hi Alan @yykk7711 , Thank you for submitting the issue.

Floating-point arithmetic can sometimes lead to precision errors due to the way computers represent real numbers. This issue is not specific to Dart; it's a common challenge in many programming languages. 

This problem is on my radar, I will look for the best solution.
I found a third-party plugin called [decimal ](https://pub.dev/packages/decimal) on pub.dev,
but I want this package to be less dependent on additional plugins. so I will try to add a method to handle this

**Comment by pmatatias** [comment]
@yykk7711  please try to use `v2.2.0`
This `0.1 + 0.1 = 0.20000000001` should not happen again.
in current version:   `0.1 + 0.1 = 0.2`


and I also added new props `decimalPlaces`. So you can specify the maximum decimal number that can be used in the widget.
```
InputQty(
   decimalPlaces: 3, // this will limit decimal, maximum 3 
   initVal: 0.0,
   minVal: -100.0,
   maxVal: 100.0,
   steps: 0.1,
),
```

**Comment by yykk7711** [comment]
Thanks @pmatatias for the very prompt upgrade, I have tested `v2.2.0` and it is well solved!
